version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

  web:
    build: .
    command: >
      bash -c "if [ ! -f tmp/initial_db_setup_done ]; then rails db:migrate && touch tmp/initial_db_setup_done; fi && rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails-docker'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

